# Generated by Django 4.2.5 on 2023-09-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_alter_expense_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="name",
            field=models.CharField(default="New expense", max_length=255),
        ),
    ]
