# Generated by Django 4.2.5 on 2023-10-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0002_income_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(),
        ),
    ]
